Feature/homework 1
asenokosov/FocusStartHomeWorks pull request #1
Opened 2020-10-24 13:35 UTC by asenokosov

реализовал консольную версию AutoCatalog

2020-10-26 06:51 UTC, korshunigor commented
Принято на проверку

2020-11-13 23:38 UTC, korshunigor commented
@Viscount88 , сменил ревьювера т.к. ты стал доступен в списке подключенных в проект

2020-11-20 06:42 UTC, Viscount88 requested changes

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/Car.swift
> +	var manufacturer: String = ""
куда-то отступы поехали

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/Car.swift
> +    var model: String = ""
А зачем ты пустое значение для строк задаешь?

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/Car.swift
> +    var yearOfIssue: String = "-"
Год выпуска и номер машины должны быть опциональными по условиям задачи

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/main.swift
> +		car.manufacturer = readLine()!
форс анврап (!) стараемся не использовать везде где можно избежать. Кроме того ты никак не обрабатываешь опциональность полей. У тебя должно быть что-то вроде 
guard let manufacturer = readLine() else { print ("Неверно указан производитель, введите ещё раз") } 
А поля год выпуска и гос номер именно опциональными, тогда там не нужен будет форс анврап. И если в них ничего нет - выводить дефолтные значения.

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/Body.swift
> +enum Body {
Смотри, тут намного лучше этому енаму присвоить тип String и для каждого значения присвоить стринговое значение, которое будет выводиться в консоль как car.body.rawValue. Вообще стринговым енамам можно даже не задавать значения, тогда строка будет соответствовать имени кейса, но т.к. кейсы у тебя английские (и это пожалуй хорошо), а вывод происходит на русском - то тут лучше всё же просто задать.

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/main.swift
> +		printChooseBody()
можно пооучение каждого отдельного поля целиком вынести в отдельный метод - так код будет намного легче читаем и это будет выглядеть как порядок команд. Например:
self.getManufacturer()
self.getModel()
...

func getManufacturer() { 
   print("Введите производителя авто")
   car.manufacturer = readLine()!
}

Ну только без форс анврапов, а как я писал выше через гвард. 
В идеале эти значения ещё лучше прогнать через какой-то форматтер или валидатор, например проверить, что введены только буквы, если это подразумевается и проверить длинну, что к примеру от 3 до 16 символов. Ну это просто навскидку пример, сам подумай для какого поля какие проверки выглядят логичными. Но с форматтерами - это опционально, не обязательно делать

2020-11-20 06:42 UTC, Viscount88 commented on FokusStartHomeWorks/main.swift
> +				var q = "", w = ""
Называй переменные так, чтобы было понятно, что она в себе содержит.  Кроме того в свифте тебе не обязательно сразу задавать ей значение. Тут вообще нормально будет смотреться функция примерно такого типа: 
func printResult(_ car: Car) {
let yearOfIssue = car.yearOfIssue ?? "-" (Для этого значение года должно быть опциональным)
let carNumberText: String? = car.carNumber ? "гос.номер: \(car.carNumber)" : nil
print("Производитель: \(car.manufacturer), Модель: \(car.model), тип корпуса: \(car.body), год выпуска: \(yearOfIssue), carNumberText"

Ну и через цикл прогоняешь как и сейчас. Кстати, сам цикл красивее будет смотреться в виде:
autoCatalog.forEach { self.printResult($0) } - у тебя для каждой машины в каталоге выполнится функция принта.

2020-11-24 09:31 UTC, Viscount88 approved these changes
Короче уже намного лучше чем было. Я оставил замечания, они в основном именно в плане оформления, это важно, но не критично. Если хочешь - поправь и залей, если нет - просто учти на будущее.

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +		let input2 = self.checkInt()
Есть набор рекомендаций по оформлению кода, называемые "чистым кодом", в частности там говорится о том, что все переменные должны иметь "говорящие названия". В данном случае input2 - это пример плохого названия, т.к. оно не говорит ничего о том, что содержит в себе. Можно назвать carBody тем же самым, как у тебя поле называется или что-то вроде того. На это обращают внимание в любом ревью, поэтому это важно.

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +			var x:Body
Насчет названий переменных везде актуально. В университете учат называть переменные x, y и тд, и потом очень сложно с этого перестроиться. Но когда имя переменной отражает её суть - код становится гораздо легче читаемым и понятным, что важно для работы в команде.

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +		else if input2 == 2 {car.body = .Sedan}
Тут можно было конечно с енамом заморочиться, т.к. если будет много вариантов кузова - запаришься их все через if - else перечислять. Но в целом и так сойдёт

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +				if car.body == x {print("Производитель: \(car.manufacturer), Модель: \(car.model), тип корпуса: \(car.body.rawValue)", "\n")}
по сути ты тут точно также показываешь список машин, как и в listAddedCars. получается можно было бы общую часть вынести в отдельный метод. К примеру можно было бы опциональный фильтр передавать, если он есть - выводить по фильтру, если нет - без. И получается везде через один метод бы работало.

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +				print(errorMessege)
Message)

2020-11-24 09:31 UTC, Viscount88 commented on FokusStartHomeWorks/Func.swift
> +		var writeString = ""
Лучше было бы сделать как с интом

2020-11-24 11:38 UTC, merged