Проект с домашним заданием 2 - Приложение, реализующее потокобезопассную коллекцию
asenokosov/FocusStartHomeWorks pull request #2
Opened 2020-10-27 11:10 UTC by asenokosov

Реализовано: 
создал и вынес в отдельный файл класс "Потокобезопасный массив".

Для него написал расширения с методами: -append(_ item:)
							               - remove(at index: Int)
								       - subscript(index: Int)
								       - contains(_ element:)
и свойствами: - IsEmpty и count.
в main происходит добавление и подсчет элементов в массиве.
в print видно что добавление в обычный массив происходит в разы быстрее и потом уже добавляются элементы в потокобезопасный массив

2020-10-28 19:33 UTC, korshunigor commented
Принято на проверку

2020-11-06 16:51 UTC, Jinfaa commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +DispatchQueue.global(qos: .background).async {
почему .background? И почему не бы не создать отдельную переменную для DispatchQueue?

2020-11-06 16:52 UTC, Jinfaa commented on ThreadSafeArray/ThreadSafeArray/StructSafeArray.swift
> +public class ThreadSafeArray<Element> {
public тут нужен?

2020-11-06 16:52 UTC, Jinfaa commented on ThreadSafeArray/ThreadSafeArray/StructSafeArray.swift
> +		queue.async(flags: .barrier) {
нужны ли [weak self] в этих блоках?

2020-11-06 16:54 UTC, Jinfaa commented on ThreadSafeArray/ThreadSafeArray/StructSafeArray.swift
> +		queue.async(flags: .barrier) {
self.queue для наглядности, что мы используем queue класса ThreadSafeArray

2020-11-06 16:55 UTC, Jinfaa requested changes
Требуются доработки

2020-11-07 04:25 UTC, asenokosov commented on ThreadSafeArray/ThreadSafeArray/StructSafeArray.swift
> +public class ThreadSafeArray<Element> {
конкретно в этом случае  нам доступ из внешних источников не обязателен. public удалил

2020-11-07 04:34 UTC, asenokosov commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +DispatchQueue.global(qos: .background).async {
.background был первый, в выпадающем списке. выбор обусловлен только этим. как я понял задание - главное чтобы качество обслуживания было одинаковым. можно было в обоих случая подставить .default или .utility.
можно было создать let queue = DispatchQueue.self, но конкретно в этом случае я решил что нет необходимости плодить сущности. можно и создать.

2020-11-07 04:50 UTC, asenokosov commented on ThreadSafeArray/ThreadSafeArray/StructSafeArray.swift
> +		queue.async(flags: .barrier) {
self для наглядности подставил, но в weak не вижу необходимости. утечек быть не должно. да и weak используется только для переменных. у нас очередь константа, а она по определению не может быть изменена в рантайме.

2020-11-14 08:40 UTC, Jinfaa approved these changes
Можно мержить

2020-11-24 11:47 UTC, merged