Третья домашняя работа. Приложение, состоящее из 3 экранов, каждый из которых содержится в UITabBar’e
asenokosov/FocusStartHomeWorks pull request #3
Opened 2020-11-05 07:49 UTC by asenokosov

Реализованы три ViewController, каждый из которых имеет TabBar. Приложение адаптировано с se(2th generation) по все остальные модели старше. 
На первом экране: Три лейбла наверху. Первый стандартный, с небольшим тестом.Второй бОльшего размера и с другим шрифтом. Третий в две строки. Ниже две кнопки: одна круглая, вторая с закруглением 8. Ниже картинка, у которой по центру крутится ActivityIndicator. Размеры соответствуют всем требованиям.
На втором экране: расположено изображение, заголовок и текст. Экран скроллится до конца текста. В горизонтальном режиме изображение находится в левом верхнем углу и имеет отступы со всех сторон. Заголовок идет по центру изображения. весь текст ниже под двумя этими элементами. 
Третий экран: содержит поля Логин/Пароль. Поведение при вводе текста: 1. Надписи Login/Password скрываются. 2. Поле Password точки при вводе. 3. Кнопка Enter поднимается над появившейся клавиатурой с небольшой задержкой через анимацию. при нажатии на пустое место на экране - клавиатура исчезает, кнопка Enter возвращается на место.

2020-11-09 18:07 UTC, korshunigor commented
Задание принято на првоерку

2020-11-13 23:50 UTC, korshunigor requested changes
Есть проблемы с самим проектом:
1) Битая ссылка на ДЗ №2 (возможно ветка создавалась когда эта проблема была в ветке с ДЗ №2, если это так, то стоит сделать git pull origin feature/homework-2 чтобы притянуть свежую версию без этой проблемы) см скрин
2) ДЗ №3 не запускается, похоже не видит Main.storyboard
3) Пул смотрит в master, опасненько)

<img width="276" alt="Снимок экрана 2020-11-14 в 02 40 36" src="https://user-images.githubusercontent.com/17854702/99131244-b2c68e80-2623-11eb-90d5-6c181ed3c8a7.png">

2020-11-14 06:26 UTC, asenokosov commented
> Есть проблемы с самим проектом:
> 
> 1. Битая ссылка на ДЗ №2 (возможно ветка создавалась когда эта проблема была в ветке с ДЗ №2, если это так, то стоит сделать git pull origin feature/homework-2 чтобы притянуть свежую версию без этой проблемы) см скрин
> 2. ДЗ №3 не запускается, похоже не видит Main.storyboard
> 3. Пул смотрит в master, опасненько)
> 
> <img alt="Снимок экрана 2020-11-14 в 02 40 36" width="276" src="https://user-images.githubusercontent.com/17854702/99131244-b2c68e80-2623-11eb-90d5-6c181ed3c8a7.png">

перезалил  main.storyboard
вторая работа уже проверяется. там были вопросы по реализации. я на них ответил. жду повторной проверки.

2020-11-14 20:55 UTC, korshunigor requested changes
Нужно поправить замечания в коде + еще несколько важных моментов которые надо исправить:
1) В этой ветке появилось 4 домашнее задание после фикса проблемы с Main.storyboard , его тут быть не должно
2) Нужно направить этот пул в ветку с ДЗ №2 (чтобы были видны только изменения сделанные в рамках этого ДЗ)

Еще можно доработать поведение кнопки Enter (в частности сделать так, чтобы при открытии клавиатуры она поднималась не на высоту клавиатуры, а поднималась ровно на столько, сколько необходимо для того чтобы клавиатура не перекрывала ее, но это по желанию.

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +
Давай делать отступы не более чем в одну пустую строку

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +	func animationIconActivity() {
Не используется, можно удалить

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +extension ViewControllerPage1 {
Можно сделать приватным

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +	func buttonSettings() {
Давай переименуем в `configureButtons`, т.к. текущее название не очень информативно (первая ассоциация - пытаемся запросить настройки кнопок)

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +			circleButton.bounds.size.width/2
Можно не переносить + перед знаком деления и после него добавь пожалуйста пробелы

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage2.swift
> +        super.viewDidLoad()
Т.к. происходит только вызов super метода, этот метод можно вовсе удалить. Да и сам класс у нас ни где ни кем не используется, по этому его можно выпилить

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +	@IBAction func enterButton(_ sender: Any) {
Т.к. нажатие ни как не обрабатывается, можно выпилить этот IBAction (удалив его и в сториборде, чтобы приложение не крошилась при нажатии).

P.s. методы должны идти уже после инициализатора (ну или в случае с UIViewController после базовых методов вроде viewDidLoad и т.д.)

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			UIView.animate(withDuration: 0.3, animations: { [self] () -> Void in
Можно упростить, вызвав:
```swift
UIView.animate(withDuration: 0.3) {
    // код который надо анимировать
}
```

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			} else {
Закрывающая скобка куда-то уползла в сторону, давай отформатируем весь файл вызвав:
1) `command + A` - выделит весь код
2) `control + I` - отформатирует выделенный код

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +							self.enterButtonConstraint.constant = enterButtonConstraint.constant - keyboardFrame.size.height + 117})
Закрывающие скобки лучше перенести на новую строку

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +				self.enterButtonConstraint.constant = keyboardFrame.size.height + 20
Сейчас у нас есть блок анимации, но если затестить, то изменение все равно происходит "рывком", для того чтобы изменение было плавным нужно добавить:
```swift
self.view.layoutIfNeeded()
```
после того как будет изменено значение констрейнта

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			if view.frame.origin.y == 0{
Потерялся пробел перед скобкой.

Давай выпилим весь лишний код (в том числе закомментированный, если он больше не нужен)

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +		enterButtonSettings.layer.borderWidth = 2.0
Подобные числа лучше выносить в константы

2020-11-14 20:55 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +extension ViewControllerPage3 {
Можно сделать приватным и сюда же вынести все методы, которые реализованы выше (во всяком случае те что используются для работы с клавиатурой)

2020-11-23 15:20 UTC, korshunigor requested changes
Давай поправим еще несколько замечаний

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +	let borderWidth: CGFloat = 2.0
Константы можно сделать приватными, ну или еще лучше вынести в enum

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +	internal override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
Т.к. override навязывает нам использование internal, мы можем удалить модификатор и вынести этот метод из приватного расширения либо в сам класс, либо создав еще одно расширение без модификатора.

P.s. на это даже сам Xcode ругается )

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +	@IBOutlet weak var labelOnTop: UILabel!
Давай выпишем неиспользуемые IBOutlet (надо будет удалить еще ссылки на них в сториборде)

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +		roundingButton.layer.cornerRadius = 8
Давай вынесем подобные значения в константы

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			UIView.animate(withDuration: 10, animations: { () -> Void in
`withDuration: 10`, это значение тоже можно вынести в константы, ну и заюзать в двух местах (тут и выше)

2020-11-23 15:20 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			})
Можно упростить опустив передачу замыкания как параметр и явный захват self:
```swift
UIView.animate(withDuration: 10) {
    self.enterButtonConstraint.constant = self.enterButtonConstraint.constant - keyboardFrame.size.height + 117
    self.view.layoutIfNeeded()
}
```

Число 117 лучше тоже вынести в константы

2020-11-25 18:16 UTC, korshunigor requested changes
Это финальные замечания вроде бы =)

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +			UIView.animate(withDuration: TimeInterval(duration)) {
Но ведь мы могли сразу объявить duration как константу типа TimeInterval, тогда не пришлось бы ее катить несколько раз (тут и ниже)

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +		enterButtonSettings.layer.borderWidth = CGFloat(ButtonSize.borderWidth)
borderWidth можно сразу объявить как константу типа CGFloat, тогда не нужно будет кастить (ниже с cornerRadius также)

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/Constants.swift
> +enum ButtonSize {
Данный enum содержит константы относящиеся только к одному экрану, по этому лучше сделать его приватным в пределах экрана к которому они относятся, чтобы в будущем мы случайно не заюзали его в каком-то другом экране.

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/Constants.swift
> +	static let ColorButtonBoreder: CGColor = UIColor.black.cgColor
1) именование переменных лучше начинать с маленькой буквы
2) тут вполне не плохо сработает выведение типа из контекста (`: CGColor` можно опустить, это не критично, просто отметил)
3) "Цвет" и "флаг" внутри "размеров кнопки" не очень вяжутся по смыслу, если enum содержит разного рода данные (как тут), то лучше использовать более абстрактные названия (допустим Constants)

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +	private let borderWidth: CGFloat = 1
Давай объединим в enum Constants

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage1.swift
> +
Давай выдерживать отступ не более 1 пустой строки

2020-11-25 18:16 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> +	private let keyboardHeight = 117
Давай объединим в enum Constants

2020-11-26 20:40 UTC, korshunigor approved these changes
Ставлю апрув, но подфикси пожалуйста оформление перед слиянием веток (сливаем только в develop и только после того как туда зальется ДЗ №2).

2020-11-26 20:40 UTC, korshunigor commented on Homework3/Homework3/ViewControllres/ViewControllerPage3.swift
> + }
Тут отступы поехали, где-то табы, где-то пробелы. Закрывающая скобка прям совсем уехала

2020-11-27 02:38 UTC, merged