Четвертая домашняя работа в которой приложение реализовано через UISplitViewController
asenokosov/FocusStartHomeWorks pull request #4
Opened 2020-11-09 06:47 UTC by asenokosov

реализован UISplitViewController, который выглядит по-разному на iPhone (4.0, 4.7, 5.8 дюйма) и на большом iPhone, iPad. При запуске приложения на айфоне появляется таблица, при запуске на большой айфоне, айпаде уже открыта таблица с выбранной первой ячейкой. В detail меню справа этот контент уже будет показываться.
В соответствии с требованиями реализовал закругление на изображениях и подложил под них тень. реализовал через отдельное расширение для UIView.

2020-11-09 12:50 UTC, noreasonwhyiamhere commented
задание принято на проверку)

2020-11-21 15:44 UTC, Jinfaa commented on HomeWork4/HomeWork4/Cell/CellsModel.swift
> +		let cellOne = CellsModel(imageFirst: UIImage(named: "andrew")!, secondImage: UIImage(named: "bence")!,
Давай в enum положим и избавимся от анвраппинга

2020-11-21 15:44 UTC, Jinfaa commented on HomeWork4/HomeWork4/Cell/CustomTableViewCell.swift
> +
новая строга

2020-11-21 15:45 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/DetailViewController.swift
> +
новая строка

2020-11-21 15:45 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/DetailViewController.swift
> +		loadViewIfNeeded()
зачем?

2020-11-21 15:46 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/MainSplitViewController.swift
> +		self.delegate = self
форматирование

2020-11-21 15:47 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +		if indexPath.row == 0 {
switch 
и не понятно что представляет из себя каждая ячейка

2020-11-21 15:49 UTC, Jinfaa commented on HomeWork4/HomeWork4/Cell/CustomTableViewCell.swift
> +
Мы можем обобщить использование классов. Сделать один единый класс

2020-11-21 15:51 UTC, Jinfaa commented on HomeWork4/HomeWork4/Cell/CellsModel.swift
> +	var imageFirst: UIImage
var -> let

2020-11-21 15:52 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +	var news = CellsModel.cellWithNews()
уровень доступа

2020-11-21 15:52 UTC, Jinfaa requested changes
Требуются доработки

2020-11-23 12:57 UTC, asenokosov commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +		if indexPath.row == 0 {
читал статью на хабре что использование if-else предпочтительней. переделал в switch.

2020-11-23 12:58 UTC, asenokosov commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +	var news = CellsModel.cellWithNews()
про это я не понял. приватным делать не вижу смысла.

2020-11-28 03:29 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +	var news = CellsModel.cellWithNews()
а публичным зачем делать?

2020-11-28 03:33 UTC, Jinfaa requested changes
Требуются доработки

2020-11-28 03:33 UTC, Jinfaa commented on HomeWork4/HomeWork4/Controllers/MainTableViewController.swift
> +	var news = CellsModel.cellWithNews()
а публичным зачем делать? И почему var?

2020-11-28 03:33 UTC, Jinfaa commented on HomeWork4/HomeWork4/SceneDelegate.swift
> +		let firstNew = masterViewController.news[0]
Нужно получить объект иначе

2020-12-01 08:05 UTC, Jinfaa commented
Когда будут доработки?

2020-12-01 08:49 UTC, asenokosov reviewed
Правки внесены

2020-12-01 08:56 UTC, asenokosov commented
> Требуются доработки

Правки внесены

2020-12-01 08:58 UTC, Jinfaa commented
Можно мрежить

2020-12-01 09:01 UTC, merged