Домашняя Работа №5
asenokosov/FocusStartHomeWorks pull request #5
Opened 2020-11-26 08:12 UTC by asenokosov

ToDoList выполнен с использованием Firebase. В качестве архитектуры использован MVVM. Приложение имеет два экрана. На первом можно залогиниться или зарегистрироваться.Второй экран содержит список задач. Можно добавить задачи через add или удалить свайпом влево. Так же можно отменить задачу как выполненную. нажав на её правый край.

2020-11-26 10:35 UTC, noreasonwhyiamhere commented
задание принято на проверку)

2020-12-21 02:52 UTC, Jinfaa commented on Homework-5/Homework-5/Controllers/TasksViewController.swift
> +	var user: TaskAndUserModel.Users!
Уровни доступа и избавиться от force unwrap

2020-12-21 03:02 UTC, Jinfaa requested changes
Требуются небольшие доработки

2020-12-21 03:02 UTC, Jinfaa commented on Homework-5/Homework-5/Controllers/LoginViewController.swift
> +		let kbFrameSize = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as! NSValue).cgRectValue
избавиться от форс анврапов

2020-12-21 03:02 UTC, Jinfaa commented on Homework-5/Homework-5/Controllers/LoginViewController.swift
> +		Auth.auth().signIn(withEmail: login, password: password, completion: {
один раз в классе вызвать  Auth.auth() будет достаточно

2020-12-21 05:42 UTC, Jinfaa commented
Мержим

2020-12-21 05:43 UTC, Jinfaa approved these changes
Мержим

2020-12-21 07:51 UTC, merged