Домашная работа №6. Паттерн "Наблюдатель"
asenokosov/FocusStartHomeWorks pull request #7
Opened 2020-12-02 03:56 UTC by asenokosov

Реализован паттерн Наблюдатель. Созданы два экрана. Для перехода между ними необходимо нажать кнопку. Для перехода обратно необходимо выбрать картинку и нажать на неё.

2020-12-02 08:20 UTC, noreasonwhyiamhere commented
задание принято на проверку

2020-12-21 03:09 UTC, Jinfaa requested changes
требуются правки

2020-12-21 03:09 UTC, Jinfaa commented on Homework-6/Homework-6/Controllers/MainViewController.swift
> +	let cat = Notification.Name(rawValue: catNotificationKey)
уровни доступа

2020-12-21 03:09 UTC, Jinfaa commented on Homework-6/Homework-6/Controllers/MainViewController.swift
> +	@IBAction func actionButtonTapped(_ sender: UIButton) {
пустой экшн?

2020-12-21 05:43 UTC, Jinfaa approved these changes
Мержим

2020-12-21 08:26 UTC, merged